### ISSUE TITLE
Azure Quick Start Template

### ISSUE THREAD

**Issue by shehackspurple** [Deliveron/owasp-zap-vsts-extension#4]
Hi!

OWASP Zap is an amazing tool.  I'd love to see it used more, and putting it in an CI/CD pipeline sounds like a fantastic plan.  It might be a bit easier if you created an Azure Quick Start template to create all of the infrastructure that is needed for this to work, personally I don't know how to do all of the steps (yet), and I'm sure other's don't either.  An Azure Quick Start template makes the whole thing few buttons.

Let me know if you'd like to talk more, I'm from MSFT.

Tanya

**Comment by mikedouglasdev** [comment]
Hi Tanya,

This is a great idea.  I working on some updated documentation for implementing this and I like the idea of including an Azure Quick Start template too.  Stay tuned.  I'll have some updates soon.

Thanks,
Mike

**Comment by biltongza** [comment]
Any updates on this?

**Comment by aldodfm** [comment]
Yes! Any update? 💃

**Comment by mikedouglasdev** [comment]
I just created a new script that uses Azure Container Instances and only needs a resource group to execute.  I'm not sure it needs to be an Azure Quick Start Template anymore. Take a look.  I'm actively working on creating all of this as an Azure DevOps extension. https://www.deliveron.com/blog/performing-a-pen-test-after-each-deployment-using-owasp-zap-azure-container-instances-and-azure-devops/

**Comment by kingthorin** [comment]
You guys should be aware of https://github.com/kasunkv/owasp-zap-vsts-task and @kasunkv’s efforts.

**Comment by michalprochnicki** [comment]
Hey Mike, what stage is the documentation updated? I would like to receive more details about the configuration from AzureDevops

**Comment by Henson0030** [comment]
How does one configure the image to ignore false positives?

**Comment by mikedouglasdev** [comment]
> How does one configure the image to ignore false positives?

Looks like I haven't implemented it yet in the newer baseline script.  It has been awhile but in the "ActiveScan" script, there is a context file parameter.  In the context file, I believe you can set how to handle false positives.  I'll put this on the list to get implemented with the newer ACI script.

**Comment by shehackspurple** [comment]
I feel like we can close my issue now.  Thank you everyone.
